#!/bin/bash

# Install minikube
if command -v minikube &> /dev/null
then
    echo "Minikube is installed"
else
    echo "Minikube is not installed. Installing...."
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
fi
