apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: itsmdsameerkhan/newsletter-backend:v1
        ports:
        - containerPort: 9000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: newsletter-secret
              key: MONGODB_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: newsletter-config
              key: BACKEND_PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstack-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
