apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newsletter-pvc
  namespace: fullstack-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: "newsletter"
      